### ISSUE TITLE
Freshdesk/v1/your_first_backend_app does not run

### ISSUE THREAD

**Issue by io41** [freshdesk/marketplace-sample-apps#1]
I just did a fresh clone of this repo and tried to run `your_first_backend_app` using the `frsh run` command. It fails with the following error:

```
> frsh run
fs.js:1387
    throw error;
    ^

Error: watch ./backend/lib ENOENT
    at exports._errnoException (util.js:1028:11)
    at FSWatcher.start (fs.js:1385:19)
    at Object.fs.watch (fs.js:1411:11)
    at /usr/local/lib/node_modules/frsh-sdk/lib/watcher.js:31:10
    at Array.forEach (native)
    at Object.watch (/usr/local/lib/node_modules/frsh-sdk/lib/watcher.js:30:11)
    at Object.run (/usr/local/lib/node_modules/frsh-sdk/lib/cli/run.js:51:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/frsh-sdk/index.js:102:30)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

The `my_first_app` app runs just fine.

I am running on macOS 10.12.4. `frsh info` report below:

```
> frsh info
# Project details:
  Platform version: v1.0

# Running on:
  SDK version: v2.3.3
  Node version: v7.6.0
```

**Comment by maheshstms** [comment]
Hi Tim,
Thanks for pointing out, we will correct the missing './backend/lib' folder.

as a work around, create the lib folder and continue 'frsh run'
$ mkdir ./backend/lib

Thanks
Mahesh

**Comment by rohitfreshdesk** [comment]
Thanks for pointing out the issue, the missing folder has now been added.
