### ISSUE TITLE
Access token not available in app.js post OAuth

### ISSUE THREAD

**Issue by plachuma** [freshdesk/marketplace-sample-apps#3]
I've set up OAuth with FB, the authorization flow works well and I'm able to find the access token in .frsh/localstore file. 
Although I am unable to get the value in my app.js when making an external request.

![screenshot from 2017-10-14 01-46-02](https://user-images.githubusercontent.com/28986446/31564645-4ebdcb30-b081-11e7-8667-28d1225b0236.png)

**Comment by raghu12133** [comment]
@plachuma Is it possible to share the whole piece of code, which will help us in figuring out the issue. And also is the request made via $request?

**Comment by plachuma** [comment]
@raghu12133 Thanks for attending this.

**Comment by raghuram-periaswamy** [comment]
@plachuma  I see two places where you are using access_token. As part of the header and in the URL. I hope the substitution of the access token in the URL fails, as it's not in the template format (<%= %>). 

Following is the correct way of representing it.

```js
'https://graph.facebook.com/v2.10/me?access_token=<%= access_token %>'
```

**Comment by plachuma** [comment]
@raghuram-periaswamy The usage in the header also failed (check screenshot in description). And also when we use it in the URL like you mentioned. 

This is the error we're getting - 

```
ReferenceError: access_token is not defined
    at eval (eval at _.template (/usr/local/lib/node_modules/frsh-sdk/node_modules/underscore/underscore.js:1454:20), <anonymous>:6:9)
    at template (/usr/local/lib/node_modules/frsh-sdk/node_modules/underscore/underscore.js:1461:21)
    at substituteTemplates (/usr/local/lib/node_modules/frsh-sdk/lib/api/proxy.js:41:59)
    at Object.execute (/usr/local/lib/node_modules/frsh-sdk/lib/api/proxy.js:20:18)
    at dpRouterExec (/usr/local/lib/node_modules/frsh-sdk/lib/routes/data-pipe.js:6:32)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/frsh-sdk/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/frsh-sdk/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/frsh-sdk/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/frsh-sdk/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/frsh-sdk/node_modules/express/lib/router/index.js:281:22
```

**Comment by nithin-raj** [comment]
Any solution to this, am also facing the same issue.

**Comment by raghu12133** [comment]
@nithin-raj There is a chance of this occurrence if the oauth_config file is removed from the project or if the features list in manifest doesn't have 'oauth'.

**Comment by nithin-raj** [comment]
@raghu12133 am working on mint UI, i hope there is no need to specify the features list in manifest. and oauth_config file is intact.

**Comment by nithin-raj** [comment]
![image](https://user-images.githubusercontent.com/1798008/33312373-b118b3cc-d44d-11e7-851f-8cd016e3110d.png)
access token not showing while debugging, but the authorization works properly.

**Comment by hemchander23** [comment]
Hope you were able to solve the issue. Closing this one. Feel free to create an issue if it persists.
